services:

  api-gateway:
    build: ./api-gateway
    ports:
      - "3000:3000"
    environment:
      - AUTH_SERVICE_URL=http://auth-service:3001
      - JOURNAL_SERVICE_URL=http://journal-service:3002
    depends_on:
      - auth-service
      - journal-service

  auth-service:
    build: ./auth-service
    ports:
      - "3001:3001"
    environment:
      - DATABASE_URL=postgresql://admin:admin@postgres:5432/authdb
      - RABBITMQ_URL=amqp://rabbitmq
    depends_on:
      mongo:
        condition: service_started
      rabbitmq:
        condition: service_healthy


  journal-service:
    build: ./journal-service
    ports:
      - "3002:3002"
    environment:
      - DATABASE_URL=mongodb://mongo:27017/journaldb
      - RABBITMQ_URL=amqp://rabbitmq
      - REDIS_URL=redis://redis:6379
    depends_on:
      mongo:
        condition: service_started
      rabbitmq:
        condition: service_healthy


  postgres:
    image: postgres
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: authdb
    ports:
      - "5433:5432"

  mongo:
    image: mongo
    ports:
      - "27018:27017"

  redis:
    image: redis
    ports:
      - "6380:6379"

  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5673:5672"
      - "15673:15672"
    #  RabbitMQ is a "heavy" service; its container might be "Running," but the internal RabbitMQ management engine takes 10–20 seconds to actually start listening on port 5672.
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "-q", "check_running"]
      interval: 5s
      timeout: 5s
      retries: 5