apiVersion: v1
kind: Service
metadata:
  name: gateway-service
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "3000"
    prometheus.io/path: "/metrics"
spec:
  selector:
    app: gateway

  ports:
    - port: 3000
      targetPort: 3000

  type: NodePort