apiVersion: v1
kind: Service
metadata:
  name: rabbitmq

spec:
  selector:
    app: rabbitmq

  ports:
    - name: amqp
      port: 5673
      targetPort: 5672

    - name: ui
      port: 15673
      targetPort: 15672